name: build module

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish-module:
    name: Run build and upload artifacts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        env: # Or as an environment variable
          GITHHUBTOKEN: ${{ secrets.GITHHUBTOKEN }}
          TOKENOWNER: ${{ secrets.TOKENOWNER }}

      - name: Install from ModuleBuilder
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ModuleBuilder,PSScriptAnalyzer
          Install-Module Pester -MinimumVersion 5.5.0

      - name: Run build.ps1
        shell: pwsh
        run: .\build.ps1
        

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-build
          path: Build

