name: build module

on: [push]

jobs:
  build-and-publish-module:
    name: Run build and upload artifacts
    runs-on: windows-latest
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v4
      
      - name: Install from ModuleBuilder
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module ModuleBuilder

      - name: Run build.ps1
      shell: pwsh
      run: .\build.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-build
          path: Build

